HomeToGo/Models/Listing.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace HomeToGo.Models;

public class Listing
{
    public int ListingId { get; set; }
    public string? UserId { get; set; }
        
    public virtual IdentityUser? User { get; set; }
        
    [StringLength(50)]
    public string Title { get; set; } = string.Empty; 
        
    [StringLength(50, MinimumLength = 4, ErrorMessage = "The address must be between 4 and 50 characters")]
    public string Address { get; set; } = string.Empty;
        
    [Range(0.01, double.MaxValue, ErrorMessage = "The price must be greater than 0.")]
    public decimal Price { get; set; }
    
    [StringLength(200)]
    public string? Description { get; set; }
    
    public string? ImageUrl { get; set; }
    
}

HomeToGo/Controllers/ListingController.cs
using HomeToGo.Models;
using HomeToGo.ViewModels;
using Microsoft.AspNetCore.Mvc;
using HomeToGo.DAL;
using Microsoft.AspNetCore.Authorization;
using Serilog;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace HomeToGo.Controllers;

// Controller for handling listings-related actions
public class ListingController : Controller
{
    // Injecting required services and repositories
    private readonly IListingRepository _listingRepository;
    private readonly ILogger<ListingController> _logger;
    private readonly UserManager<IdentityUser> _userManager;

    public ListingController(IListingRepository listingRepository, ILogger<ListingController> logger, UserManager<IdentityUser> userManager)
    {
        _listingRepository = listingRepository ?? throw new ArgumentNullException(nameof(listingRepository));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
    }

    // Displays all listings in a table format
    public async Task<IActionResult> Table()
    {
        var listings = await _listingRepository.GetAll();
        if (listings == null)
        {
            _logger.LogError("[ListingController] Listing list not found while executing _listingRepository.GetAll()");
            return NotFound("Listing list not found");
        }
        var listingListViewModel = new ListingListViewModel(listings, "Table");
        return View(listingListViewModel);
    }

    // Displays all listings in a grid format
    public async Task<IActionResult> Grid()
    {
        var listings = await _listingRepository.GetAll();
        if (listings == null)
        {
            _logger.LogError("[ListingController] Listing list not found while executing _listingRepository.GetAll()");
            return NotFound("Listing list not found");
        }
        var listingListViewModel = new ListingListViewModel(listings, "Grid");
        return View(listingListViewModel);
    }

    // Displays details for a specific listing
    public async Task<IActionResult> Details(int id)
    {
        var listing = await _listingRepository.GetListingById(id);
        if (listing == null)
        {
            _logger.LogError("[ListingController] Listing list not found while executing _listingRepository.GetAll()");
            return NotFound("Listing list not found");
        }

        return View(listing);
    }

    // Presents the form for creating a new listing
    [HttpGet]
    [Authorize]
    public IActionResult Create()
    {
        return View();
    }

    // Handles the submission of the new listing form
    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Create(Listing listing)
    {
        if (ModelState.IsValid)
        {
            listing.UserId = _userManager.GetUserId(User); // Setting the UserId for the listing
            bool returnOk = await _listingRepository.Create(listing);
            if (returnOk)
                return RedirectToAction(nameof(Table));
        }
        _logger.LogWarning("[ListingController] Listing creation failed {@listing}", listing);
        return View(listing);
    }

    // Presents the form for updating an existing listing
    [HttpGet]
    [Authorize]
    public async Task<IActionResult> Update(int id)
    {
        var listing = await _listingRepository.GetListingById(id);
        if (listing == null)
        {
            _logger.LogError("[ListingController] Listing not found when updating the ListingId {ListingId:0000}", id);
            return BadRequest("Listing not found for the ListingId");
        }

        return View(listing);
    }

    // Handles the submission of the update listing form
    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Update(Listing listing)
    {
        if (ModelState.IsValid)
        {
            bool returnOk = await _listingRepository.Update(listing);
            if (returnOk)
                return RedirectToAction(nameof(Table));
        }
        _logger.LogWarning("[ListingController] Listing update failed {@listing}", listing);
        return View(listing);
    }

    // Presents the confirmation form for deleting a listing
    [HttpGet]
    [Authorize]
    public async Task<IActionResult> Delete(int id)
    {
        var listing = await _listingRepository.GetListingById(id);
        if (listing == null)
        {
            _logger.LogError("[ListingController] Listing not found for the ListingId {ListingId:0000}", id);
            return BadRequest("Listing not found for the ListingId");
        }

        return View(listing);
    }

    // Handles the confirmation of listing deletion
    [HttpPost]
    [Authorize]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var listing = await _listingRepository.GetListingById(id);
        if (listing == null)
        {
            _logger.LogError("[ListingController] Listing deletion failed for the ListingId {ListingId:0000}", id);
            return BadRequest("Listing deletion failed");
        }

        await _listingRepository.Delete(id);
        return RedirectToAction(nameof(Table));
    }
}

HomeToGo/Controllers/ReservationController.cs
using HomeToGo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HomeToGo.DAL;
using HomeToGo.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace HomeToGo.Controllers;

// Controller to handle reservations.
public class ReservationController : Controller
{
    // Logging, database context, and user manager dependencies.
    private readonly ILogger<ReservationController> _logger;
    private readonly ListingDbContext _listingDbContext;
    private readonly UserManager<IdentityUser> _userManager;

    // Constructor to inject dependencies.
    public ReservationController(ListingDbContext listingDbContext, ILogger<ReservationController> logger,
        UserManager<IdentityUser> userManager)
    {
        _listingDbContext = listingDbContext;
        _logger = logger;
        _userManager = userManager;
    }

    // Helper method to calculate total price of a reservation.
    private async Task CalculateTotalPrice(Reservation reservation)
    {
        // Validations
        if (reservation == null) throw new ArgumentNullException(nameof(reservation), "Reservation cannot be null");
        if (reservation.ListingId == null) throw new ArgumentException("Reservation must have a ListingId");

        var listing = await _listingDbContext.Listings.FindAsync(reservation.ListingId);
        if (listing == null) throw new ArgumentException("Invalid ListingId in Reservation");

        // Calculate total price
        TimeSpan stayDuration = reservation.CheckOutDate - reservation.CheckInDate;
        reservation.TotalPrice = listing.Price * stayDuration.Days;
    }

    // Helper method to check if a reservation overlaps with existing ones.
    private async Task<bool> IsReservationOccupied(Reservation newReservation)
    {
        return await _listingDbContext.Reservations.AnyAsync(r => r.ListingId == newReservation.ListingId &&
                                                                  r.ReservationId != newReservation.ReservationId &&
                                                                  ((newReservation.CheckInDate >= r.CheckInDate &&
                                                                    newReservation.CheckInDate < r.CheckOutDate) ||
                                                                   (newReservation.CheckOutDate > r.CheckInDate &&
                                                                    newReservation.CheckOutDate <= r.CheckOutDate) ||
                                                                   (newReservation.CheckInDate <= r.CheckInDate &&
                                                                    newReservation.CheckOutDate >= r.CheckOutDate)));
    }

    // Displays all reservations in a table view.
    public async Task<IActionResult> Table()
    {
        var reservations = await _listingDbContext.Reservations.Include(r => r.Listing).ToListAsync();
        foreach (var reservation in reservations) await CalculateTotalPrice(reservation);

        return View(reservations);
    }

    // GET: Create a reservation.
    [HttpGet]
    public async Task<IActionResult> CreateReservation()
    {
        // Preparing data for dropdowns in the view
        var users = await _listingDbContext.Users.ToListAsync();
        var listings = await _listingDbContext.Listings.ToListAsync();

        var createReservationViewModel = new CreateReservationViewModel
        {
            Reservation = new Reservation(),
            UserSelectList = users.Select(user => new SelectListItem
            {
                Value = user.Id.ToString(),
                Text = user.UserName
            }).ToList(),
            ListingSelectList = listings.Select(listing => new SelectListItem
            {
                Value = listing.ListingId.ToString(),
                Text = listing.Title
            }).ToList(),
        };

        return View(createReservationViewModel);
    }

    // POST: Create a reservation.
    [HttpPost]
    [Authorize]
    public async Task<IActionResult> CreateReservation(CreateReservationViewModel model)
    {
        try
        {
            // Removing unnecessary model validations
            ModelState.Remove("Reservation.UserId");
            ModelState.Remove("Reservation.User");

            if (!ModelState.IsValid)
            {
                var loggedInUser = await _userManager.GetUserAsync(User);
                if (loggedInUser == null) return Unauthorized("No logged-in user found.");
                model.Reservation.UserId = loggedInUser.Id;

                // Checking if reservation dates are available
                if (await IsReservationOccupied(model.Reservation))
                {
                    ModelState.AddModelError(string.Empty, "The reservation is occupied for the selected dates.");
                    _logger.LogError("[ReservationController] The reservation is occupied for the selected dates");
                }
                else
                {
                    // Fetching user and listing, and validating
                    var user = await _listingDbContext.Users.FindAsync(model.Reservation.UserId);
                    var listing = await _listingDbContext.Listings.FindAsync(model.Reservation.ListingId);

                    if (user == null) ModelState.AddModelError("Reservation.UserId", "User not found.");
                    if (listing == null) ModelState.AddModelError("Reservation.ListingId", "Please select a listing.");

                    if (user != null && listing != null)
                    {
                        _listingDbContext.Reservations.Add(model.Reservation);
                        await _listingDbContext.SaveChangesAsync();
                        return RedirectToAction(nameof(Table));
                    }
                }
            }
        }
        catch (Exception e)
        {
            _logger.LogError($"[ReservationController] Reservation creation failed for listing {model.Reservation.ListingId}, error message: {e.Message}");
            ModelState.AddModelError(string.Empty, "Error creating reservation.");
        }

        // Load lists for dropdowns in case of error
        model.UserSelectList = await _listingDbContext.Users.Select(user => new SelectListItem
        {
            Value = user.Id.ToString(),
            Text = user.UserName
        }).ToListAsync();

        model.ListingSelectList = await _listingDbContext.Listings.Select(listing => new SelectListItem
        {
            Value = listing.ListingId.ToString(),
            Text = listing.Title
        }).ToListAsync();

        return View(model);
    }

    // GET: Delete a reservation.
    [HttpGet]
    public async Task<IActionResult> DeleteReservation(int id)
    {
        var reservation = await _listingDbContext.Reservations.Include(r => r.Listing).Include(r => r.User).FirstOrDefaultAsync(r => r.ReservationId == id);
        if (reservation == null)
        {
            _logger.LogError("[ReservationController] Reservation not found");
            return NotFound("Reservation not found");
        }

        await CalculateTotalPrice(reservation); // Calculate TotalPrice before passing to the view
        return View(reservation);
    }

    // POST: Confirm deletion of a reservation.
    [HttpPost]
    [Authorize]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var reservation = await _listingDbContext.Reservations.FindAsync(id);
        if (reservation == null)
        {
            _logger.LogError("[ReservationController] Reservation not found");
            return NotFound("Reservation not found");
        }

        _listingDbContext.Reservations.Remove(reservation);
        await _listingDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Table));
    }
}

HomeToGo/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

// Controller to manage user-related actions.
public class UserController : Controller
{
    // Dependency on UserManager to interact with user data.
    private readonly UserManager<IdentityUser> _userManager;

    // Constructor to inject UserManager dependency.
    public UserController(UserManager<IdentityUser> userManager)
    {
        _userManager = userManager;
    }

    // Action to display a list of users.
    public async Task<IActionResult> Users()
    {
        // Retrieve all users from the database.
        var users = await _userManager.Users.ToListAsync();

        // Render the user list view with the retrieved users.
        return View("~/Views/Shared/_UserTable.cshtml", users);
    }
}

HomeToGo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeToGo</title>
    <link rel="icon" href="~/Images/icons8-home.svg" type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HomeToGo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img class="icon" src="~/Images/icons8-home.svg">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeToGo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark hove" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Listing" asp-action="Grid">Listings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Users">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="Table">Reservation</a>
                        </li>
                           
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @RenderSection("Scripts", required: false)
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - HomeToGo - 
            <a asp-area="" asp-controller="Listing" asp-action="Grid">Listings</a> -
            <a asp-area="" asp-controller="User" asp-action="users">Users</a> -
            <a asp-area="" asp-controller="Reservation" asp-action="Table">Reservations</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

HomeToGo/Views/Shared/_ListingCard.cshtml
@model Listing

<div class="col">
    <a href="/Listing/Details/@Model.ListingId" class="card-link">
        <div class="card h-100">
            <img src="@Model.ImageUrl" class="card-img-top" alt="@Model.Title">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text">@Model.Description</p>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-between">
                    <h6>@Model.Price.ToString("0.00 Nok")</h6>
                </div>
            </div>
        </div>
    </a>
</div>

HomeToGo/Views/Shared/_ListingTable.cshtml
@model IEnumerable<Listing>

<div class="table-responsive">
    <table class='table table-striped table-hover align-middle'>
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Address</th>
                <th>Price</th>
                <th>Description</th>
                <th>Host</th>
                <th>Image</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var listing in Model)
            {
                <tr>
                    <td>@listing.ListingId</td>
                    <td> <a class="link-primary"  asp-controller="Listing" 
                            asp-action="Details"
                            asp-route-id="@listing.ListingId">@listing.Title</a></td>
                    <td>@listing.Address</td>
                    <td>@listing.Price.ToString(("0.00 Nok"))</td>
                    <td>@listing.Description</td>
                    <td>@(listing.User?.Email ?? "N/A")</td>
                    <td>
                        <img src="@listing.ImageUrl" alt="Listing Image" style="max-width: 80px; max-height: 80px;"/>
                    </td>
                    <td>
                        <a class="btn btn-secondary" asp-controller="Listing" asp-action="Update" asp-route-id="@listing.ListingId">Update</a>
                        <a class="btn btn-danger" asp-controller="Listing" asp-action="Delete" asp-route-id="@listing.ListingId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<p class="mt-3">
    <a class="btn btn-primary"
        asp-controller="Listing"
        asp-action="Create">Create New Item</a>
</p>

HomeToGo/Views/Shared/_ReservationItemTable.cshtml
@model IEnumerable<ReservationListing>

<div class="container">
    <table class='table table-striped' style='max-width: 1200px;'>
        <tr>
            <th>ListingId</th>
            <th>Title</th>
            <th>Address</th>
            <th>Price</th>
            <th>Description</th>
        </tr>
        
        @foreach (var reservationListing  in Model)
        {
            <tr>
               <td>@reservationListing.Reservation.ListingId</td>
               <td>@reservationListing.ReservationId</td>
            </tr>
        }
    </table>
</div>

HomeToGo/Views/Shared/_UserTable.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityUser>
<h1>List of Users</h1>

<div class="container">
    <table class="table-user table-striped">
        <thead>
        <tr>
            <th>User Name</th>
            <th>Phone Number</th>
            <th>Email Confirmed</th>
            <th>Two Factor Enabled</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.UserName</td>
                <td>@user.PhoneNumber</td>
                <td>@(user.EmailConfirmed ? "Yes" : "No")</td>
                <td>@(user.TwoFactorEnabled ? "Yes" : "No")</td>
            </tr>
        }
        </tbody>
    </table>
</div>

HomeToGo/Views/Shared/slides.cshtml
<div id="carouselImages" class="carousel slide" data-bs-ride="true">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselImages" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item">
            <img src="~/images/Ap1.jpg" class="d-block w-100" alt="Image 1">
        </div>
        <div class="carousel-item active">
            <img src="~/images/Ap5.jpg" class="d-block w-100" alt="Image 2">
        </div>
        <div class="carousel-item">
            <img src="~/images/Ap2.jpg" class="d-block w-100" alt="Image 3">
        </div>
            <a class="book-button" asp-controller="Listing" asp-action="Grid">Book Today</a>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselImages" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselImages" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>